# PostgreSQL. Versions 7.4 and 8.x are supported.
common: &common
  adapter: postgresql
  encoding: unicode
  pool: 5
  username: recipe_box
  password: recipe_box

development:
  <<: *common
  database: recipe_box_development

test:
  <<: *common
  database: recipe_box_test

production:
  <<: *common
  database: recipe_box_production
